server:
  port: 8760

spring:
  profiles:
    active: dev
  web:
    resources:
      add-mappings: false

  application:
    name: gateway

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    tags:
      application: ${spring.application.name}