spring:
  cloud:
    ##===== consul configuration =====##
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: false

  mail:
    host: smtp.163.com
    username: xx1@xx.com
    password: xx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  ##=====mongodb config=====##
  data:
    mongodb:
      host: 127.0.0.1
      port: 123456
      username: xxxx
      password: xxxx
      database: xxxx
      authentication-database: xxxx